---

- hosts: all
  gather_facts: true
  
  user: ubuntu
  become: true
  become_user: root
  
  roles:
    - python-simplejson # required for ansible
    - python3-pip-virtualenv
    - nginx
    - role: oracle-java
      oracle_java_set_as_default: yes
    - xlsform
